-- CreateEnum
CREATE TYPE "OrderStatusEnum" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'ON_HOLD', 'SHIPPED', 'DELIVERED', 'REFUND_REQUESTED', 'REFUND_REJECTED', 'REFUND_APPROVED', 'REFUNDED', 'PARTIALLY_COMPLETED');

-- CreateTable
CREATE TABLE "OrderLog" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "status" "OrderStatusEnum" NOT NULL DEFAULT 'PENDING',
    "comment" TEXT,

    CONSTRAINT "OrderLog_pkey" PRIMARY KEY ("id")
);
